# -*- coding: utf-8 -*-
"""Machine learing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew0457IVb9wbxDm8QZpn0yi4Ua5msQFJ
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

df=pd.read_csv("/content/sample_data/cleaned_merged_heart_dataset.csv")

df.head()

df.describe()

df.isnull().sum()

df.isnull()

df.info()

df.tail()

df.isnull()

df.info()

df.describe()

df.isnull().sum()

df.isnull().sum()

df.info()

df.shape

df.columns

df['age'].value_counts()

df['fbs'].value_counts()

df['oldpeak'].value_counts()

df.tail()

df.value_counts()

df.columns

x=df['target']

x

y=df['target']

y

from sklearn.model_selection import train_test_split

df.dtypes

from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

label

label.fit(df['target'])

label.transform(df['target'])

ary1=label.transform(df['target'])

ary1

df['target']= ary1

df

df.drop("target",inplace=True,axis=1)

df

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
X = df
y = ary1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Random Forest Classifier Accuracy: {accuracy:.4f}")